"""
PlatformIO pre-build script.
Generates:
  - build_timestamp.txt  : plain-text record in project root
  - src/build_ts_gen.h   : C header included by config.cpp

Both contain the same DDMMYYYYHHMM string.  Because src/build_ts_gen.h
changes on EVERY build, config.cpp is always recompiled, ensuring the
firmware BUILD_TIMESTAMP matches build_timestamp.txt exactly.

The code runs at script-import time (top level) so the header exists
before the compiler touches config.cpp.
"""
Import("env")
from datetime import datetime
import os

now = datetime.now()
ts  = now.strftime("%d%m%Y%H%M")
root = env.subst("$PROJECT_DIR")

# 1. Plain text record
with open(os.path.join(root, "build_timestamp.txt"), "w") as f:
    f.write(ts + "\n")

# 2. C header — changing this file forces config.cpp to recompile
header = os.path.join(root, "src", "build_ts_gen.h")
with open(header, "w") as f:
    f.write("// Auto-generated by scripts/gen_build_ts.py -- DO NOT EDIT\n")
    f.write("#pragma once\n")
    f.write('#define BUILD_TS_STR "' + ts + '"\n')

print("[gen_build_ts] build_timestamp.txt + build_ts_gen.h -> " + ts)
